### ISSUE TITLE
Convert from seurat object

### ISSUE THREAD

**Issue by sailseem** [jbergenstrahle/STUtility#20]
Dear developer,

Just wondering is there any function to convert STUtility object directly from seurat?
And how to subset cells by applying some gene expression more than 1, like in seurat, which could be like xx<-subset(seurat, gene>1)

Thanks a lot for you help.

**Comment by ludvigla** [comment]
Hi there,

STUtility only works with Seurat objects, so if you mean that you want to convert it into a Seurat object, you don't have to since it already is one. However, you cannot use the "spatial functions" from Seurat on a Seurat object created with STUtility. Unfortunately, you'll have to create a new object following the Seurat workflow.

You can subset data with the SubsetSTData function. You can find a tutorial here: https://ludvigla.github.io/STUtility_web_site/Subset_and_Merge.html

Cheers,
Ludvig

**Comment by sailseem** [comment]
Thanks for your reply. But i am wondering how to subset cells based on gene expression, which is not included in your tutorial.

**Comment by sailseem** [comment]
sorry, just ignore what i was saying, i figure out how to make it work. Thanks!!!
